baseurl = "http://ifels.cn"
languageCode = "en-us"
title = "ifels's blog"
canonifyurls = true

[params]
    sidebartitle = "ifels"
    sidebartagline = "coding life"
    disqusShortname = "ifels.cn"
    highlightStyle = "solarized_dark"

[[menu.main]]
    name = "Blog"
    url = "/post"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "http://www.twitter.com/ifels"
    identifier = "twitter"

[[menu.footer]]
    name = "Blog"
    url = "/posts"
